### ISSUE TITLE
overflow-x: scrol

### ISSUE THREAD

**Issue by nikanoza** [tinatinnnn/site#1]
![image](https://github.com/user-attachments/assets/8b8e9848-8b9e-4e5a-822a-24129c13a5f2)
სურათის გამო ცდება ეკრანის ზომებს და უჩნდება ჰორიზონტარული სქროლი

**Comment by tinatinnnn** [comment]
მობილურზე გულისხომ?

**Comment by nikanoza** [comment]
როცა შევამოწმე ისედაც მარტო მობილურის ვერსია იყო აწყობილი
