### ISSUE TITLE
ზომები

### ISSUE THREAD

**Issue by nikanoza** [tinatinnnn/site#5]
![image](https://github.com/user-attachments/assets/9ee856f1-4fae-4ec1-9850-d9b685bc03f9)
ნუ წერ მთლიანი ეკრანის ზომებს პიქსელებშI, არ შეიძლება !
body უნდა ქონდეს ზომა width:100vw , და ყველა შვილ ელემენტს საჭიროებისამებრ პროცენტებში

**Comment by tinatinnnn** [comment]
375px rom uweria ra unda davuwero aba
